name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: issue_comment
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    env:
      PR_NUMBER: ${{ github.event.issue.number }}
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $PR_NUMBER